export const types = {
  Grass: false,
  Poison: false,
  Fire: false,
  Flying: false,
  Water: false,
  Bug: false,
  Normal: false,
  Electric: false,
  Ground: false,
  Fighting: false,
  Psychic: false,
  Rock: false,
  Ice: false,
  Ghost: false,
  Dragon: false,
};

export const weaknesses = {
  Fire: false,
  Ice: false,
  Flying: false,
  Psychic: false,
  Water: false,
  Ground: false,
  Rock: false,
  Electric: false,
  Grass: false,
  Fighting: false,
  Poison: false,
  Bug: false,
  Fairy: false,
  Ghost: false,
  Dark: false,
  Steel: false,
  Dragon: false,
};
